# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. 
Why you would want to use Arrays instead of lists?
- Advantage of Numpy:
    - Scalability: save room and time
    - Functionality: a lot built-in function.

- Disadvantage of Numpy compare to list:
    - less flexibity, since Numpy requires its elements are of the same type. Note that Numpy will cast the datatype silently.

also see [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.array([range(i, i+3) for i in range(0, 4)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note** : the Numpy array can only contain the elements with the same datatype. it will cast its element to certain datatype silently.

In [24]:
np.array([3.14, 2, 3, 4])

array([3.14, 2.  , 3.  , 4.  ])

In [10]:
my_list = np.arange(0, 10)
my_list[3] = 100.2
my_list

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.arange(11, 0, -1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### zeros and ones and full

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:
np.full((2, 3), 5.6)

array([[5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6]])

In [32]:
np.empty(3)

array([1., 1., 1.])

### linspace
Return evenly spaced numbers over a specified interval.

In [29]:
np.linspace(0,10,3) # the third parameter is the len of the list.

array([  0.,   5.,  10.])

In [27]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
np.eye(3,5,0) # the third parameter is the location of the diagonal. 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(2)

array([0.82242978, 0.25483677])

In [23]:
np.random.rand(5,5)

array([[0.52602034, 0.01155415, 0.60605427, 0.05480285, 0.50386102],
       [0.76154339, 0.59911171, 0.91123467, 0.91067745, 0.84666989],
       [0.64378278, 0.29963768, 0.52522315, 0.7161517 , 0.52242939],
       [0.37327624, 0.32921836, 0.64091467, 0.5232876 , 0.34472023],
       [0.31892881, 0.59744259, 0.35852412, 0.28378009, 0.9129625 ]])

### random

There is no parameter for the range, they are always 0 to 1.

Note the difference in passing the parameter to create a matrix comparing to **rand**.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).


In [40]:
np.random.random(2)

array([0.12449596, 0.87760717])

In [41]:
np.random.random((3,3))

array([[0.70059472, 0.35303272, 0.27795262],
       [0.41482717, 0.29135107, 0.23035937],
       [0.42979714, 0.6740778 , 0.76738697]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [36]:
np.random.randn(2)

array([0.13451005, 0.29398337])

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### normal

In [37]:
np.random.normal(0, 1, 2)

array([1.60818736, 0.9432003 ])

In [38]:
np.random.normal(0, 1, (3, 3))

array([[ 0.80633433,  1.93955777,  0.24456994],
       [-0.95128259, -1.06002154, -0.79535805],
       [ 0.76605033, -0.24752378, -1.00103195]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [50]:
np.random.randint(1,100)

44

In [51]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

We'll cover a few categories of basic array manipulations here:

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array
- Reshaping of arrays: Changing the shape of a given array
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [63]:
arr = np.arange(5)
ranarr = np.random.randint(0,50,5)

In [64]:
arr

array([0, 1, 2, 3, 4])

In [65]:
ranarr

array([47,  0, 20, 42, 39])

## Common-used attributes (the one without parentheses)

In [66]:
arr.ndim

1

In [67]:
arr.shape

(5,)

In [68]:
arr.size

5

In [69]:
arr.dtype

dtype('int32')

In [70]:
arr.itemsize

4

In [71]:
arr.nbytes

20

## max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [72]:
ranarr

array([47,  0, 20, 42, 39])

In [73]:
ranarr.max()

47

In [74]:
ranarr.argmax()

0

In [75]:
ranarr.min()

0

In [76]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [82]:
# Vector, note the different with the 1-D matrix
arr.shape

(5,)

## Reshape
Returns an array containing the same data with a new shape. it will use a no-copy view of the initial array when possible.

In [83]:
# Notice the two sets of brackets, this is not a in-place change
arr.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [84]:
arr.reshape(1,5).shape

(1, 5)

In [93]:
arr[np.newaxis, :] # in this way, you don't have to know the len of the vector.

array([[  0,   1, 100,   3,   4]])

**Note** : the reshape function is generating a no-copy view.

In [87]:
arr.reshape(1,5)[0][2] = 100

In [88]:
arr

array([  0,   1, 100,   3,   4])

In [90]:
arr.reshape(5,1)

array([[  0],
       [  1],
       [100],
       [  3],
       [  4]])

In [91]:
arr.reshape(5,1).shape

(5, 1)

In [94]:
arr[:, np.newaxis] # in this way, you don't have to know the len of the vector.

array([[  0],
       [  1],
       [100],
       [  3],
       [  4]])

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

In [98]:
np.zeros(10, dtype = 'int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
np.zeros(10, dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

|Data type	|Description|
|--|--|
|bool_	|Boolean (True or False) stored as a byte|
|int_	|Default integer type (same as C long; normally either int64 or int32)|
|intc	|Identical to C int (normally int32 or int64)|
|intp	|Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8	|Byte (-128 to 127)|
|int16	|Integer (-32768 to 32767)|
|int32	|Integer (-2147483648 to 2147483647)|
|int64	|Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	|Unsigned integer (0 to 255)|
|uint16	|Unsigned integer (0 to 65535)|
|uint32	|Unsigned integer (0 to 4294967295)|
|uint64	|Unsigned integer (0 to 18446744073709551615)|
|float_	|Shorthand for float64.|
|float16	|Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32	|Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64	|Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_	|Shorthand for complex128.|
|complex64	|Complex number, represented by two 32-bit floats|
|complex128	|Complex number, represented by two 64-bit floats|